### PR TITLE
Friendship v1

### PR DESCRIPTION
**Pull request by ajkacca457**
In this milestone, I implemented the following features for a logged-in user :

A user is able to see all users list.
A user is able to send a friendship request.
A user can see a button “Add friend” next to the name of the user who is not his friend yet.
A user is able to see all the friendship requests sent to him from other users.
A user is able to accept or remove friendships requests.

### CODE REVIEW

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

Hello @ajkacca457, Great job! 👏  I am really impressed with your work, keep it up.
Let's make a few changes, and we will be done with this milestone.

- [x] There is a button to invite user to friendship on users list page ✅  and on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). There is one on the user list page, just add an invite button at user profile page. That shouldn't be a problem, do this and you should be good to go.

Nice job! once again.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Comment by ajkacca457** [comment]
@acushlakoncept Thank you very much for your kind review. I really appreciate it.  The invitation button added to the user profile based on your review.

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Avi Karmaker** 
Good job with the improvements for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
Just a couple of details to improve before you can go ahead:

- [ ]  “Timeline” page should show the total number of likes for each post (from the current user and their friends).
- [ ] Add a screenshot in the README file.

 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by ajkacca457** [comment]
@andresporras3423 thanks for your review. I have added the numbers of likes with every post. I have inserted a screenshot of the project in the readMe file.

**Review by kitpao — APPROVED** [review]
# 👋 Hello @ajkacca457 

Great job so far! You have complied with the requirements 😄 

**_Note:_** All the **[OPTIONAL]** are **not required** in order to approve your project but are personal suggestions to improve your coding experience

- [x] **OPTIONAL** Just a hint for the next milestone: you will be asked to refactor your code, to test the functionality without having to manually check that nothing broke with the changes, you can do tests for your current logic (because you already know it works) with rspec & capybara, and then do the refactoring(it will be required in this project anyways) and check if they are passing :)

### 👏 Congratulations 🥳 Your project has been approved 👏
### 🚀 You may merge to development and submit the project completition form 🚀

___
##### 👉 If you have any doubts you can contact me on slack as @kitpao
##### 🌟  If you have feedback about my reviews I would appreciate it if you could leave a recommendation in LinkedIn 💌 or let me know in Slack if you see improvements to be done 😄  

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

**Pull request merged**
