### PR TITLE
Friendship v2

### PR DESCRIPTION
**Pull request by ajkacca457**
- Mutual friendship function exists.
- Like counts exist and styling added.
- Tests added.

### CODE REVIEW

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

### Hello @ajkacca457, Great job! 👏  

You've done an awesome job so far 👌. But there are still some changes that are necessary for this project to be approved.

- [ ] I think it won't be a bad idea to update your readme file with the Author name and some other TBA

- [ ] When I send a friend request, I do not see Accept Friend Request, but just Delete Request, kindly fix your logic.

- [ ] In order to get all posts written by a user and their friends, you can use a simple method in your User model 
```ruby
def friends_and_own_posts
  Post.where(user: (self.friends + self))
end
```
- [ ] Two of your test are failing: 
** Failure/Error: click_link('Friend Requests') : Unable to find link "Friend Requests"
**  Failure/Error: fill_in('user[email]', with: 'friend1@example.com') : Unable to find field "user[email]" that is not disabled

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Comment by ajkacca457** [comment]
@acushlakoncept  thanks for your kind review. I have added a friendship accept button in the friend requests section.  I have updated the readMe file. Restructured the show posts model. I have checked with RSpec whether the tests are running properly. Hopefully, I was successful in improving the project based on your review.

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Hi @ajkacca457! You have done a great job implementing the suggested changes from the last review. :ok_hand: There are just a few errors in your test suite. They are caused by capybara failing to find the necessary elements you used in your integration tests. Please double check that the elements you refer to in your integration tests exist in the views.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by ajkacca457** [comment]
@trekab thanks for your review. I have fixed the RSpec issue and on my computer, there is no rspec error showing.

**Review by rOluochKe — APPROVED** [review]
Hello @ajkacca457 
### You got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one. 
- Happy coding!

**Pull request merged**
